# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=models.FileField(upload_to='posts/', verbose_name='Картинка статьи'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_img',
            field=models.FileField(upload_to='questions/', verbose_name='Картинка вопроса'),
        ),
    ]
