# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170406_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='height_img',
            field=models.IntegerField(default=0, verbose_name='Длинна картинки'),
        ),
        migrations.AddField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 17, 58, 18, 284459, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='posts',
            name='width_img',
            field=models.IntegerField(default=0, verbose_name='Ширина картинки'),
        ),
        migrations.AddField(
            model_name='questions',
            name='height_img',
            field=models.IntegerField(default=0, verbose_name='Длинна картинки'),
        ),
        migrations.AddField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 17, 58, 18, 305460, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='questions',
            name='width_img',
            field=models.IntegerField(default=0, verbose_name='Ширина картинки'),
        ),
    ]
