# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170406_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 18, 1, 40, 195007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 18, 1, 40, 217008, tzinfo=utc)),
        ),
    ]
