# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170406_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_answer',
            field=models.TextField(default='', verbose_name='Ответ'),
        ),
    ]
