# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170407_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_short',
            field=models.TextField(default=''),
        ),
    ]
